# Generated by Django 2.0.13 on 2019-12-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppG2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='usuario',
            new_name='solicitante',
        ),
    ]
